import { useLanguage } from "./LanguageContext"
import { useTheme } from "./ThemeConext";

function Wellcome(){
    const { Language } = useLanguage();
    const {theme , toggleTheme} = useTheme();
    const Translate = {
        en: {
            welcome: "Welcome to our site!",
            logout: "Logout",
            login: "Login",
            signup: "Sign Up",
            home: "Home",
            about: "About Us",
            contact: "Contact",
            books: "Books",
            cart: "Cart",
            profile: "Profile",
            settings: "Settings",
            search: "Search",
            addBook: "Add Book",
            remove: "Remove",
            update: "Update",
            language: "Language",
            help: "Help",
            terms: "Terms of Service",
            privacy: "Privacy Policy",
        },
        ur: {
            welcome: "ہماری ویب سائٹ پر خوش آمدید!",
            logout: "لاگ آؤٹ",
            login: "لاگ ان",
            signup: "سائن اپ",
            home: "ہوم",
            about: "ہمارے بارے میں",
            contact: "رابطہ کریں",
            books: "کتابیں",
            cart: "ٹوکری",
            profile: "پروفائل",
            settings: "ترتیبات",
            search: "تلاش کریں",
            addBook: "کتاب شامل کریں",
            remove: "ہٹائیں",
            update: "اپ ڈیٹ کریں",
            language: "زبان",
            help: "مدد",
            terms: "سروس کی شرائط",
            privacy: "رازداری کی پالیسی",
        },
        es: {
            welcome: "¡Bienvenido a nuestro sitio!",
            logout: "Cerrar sesión",
            login: "Iniciar sesión",
            signup: "Regístrate",
            home: "Inicio",
            about: "Sobre nosotros",
            contact: "Contacto",
            books: "Libros",
            cart: "Carrito",
            profile: "Perfil",
            settings: "Configuración",
            search: "Buscar",
            addBook: "Agregar libro",
            remove: "Eliminar",
            update: "Actualizar",
            language: "Idioma",
            help: "Ayuda",
            terms: "Términos de servicio",
            privacy: "Política de privacidad",
        },
        fr: {
            welcome: "Bienvenue sur notre site!",
            logout: "Se déconnecter",
            login: "Connexion",
            signup: "S'inscrire",
            home: "Accueil",
            about: "À propos",
            contact: "Contact",
            books: "Livres",
            cart: "Panier",
            profile: "Profil",
            settings: "Paramètres",
            search: "Recherche",
            addBook: "Ajouter un livre",
            remove: "Supprimer",
            update: "Mettre à jour",
            language: "Langue",
            help: "Aide",
            terms: "Conditions d'utilisation",
            privacy: "Politique de confidentialité",
        },
        de: {
            welcome: "Willkommen auf unserer Seite!",
            logout: "Ausloggen",
            login: "Anmelden",
            signup: "Registrieren",
            home: "Startseite",
            about: "Über uns",
            contact: "Kontakt",
            books: "Bücher",
            cart: "Warenkorb",
            profile: "Profil",
            settings: "Einstellungen",
            search: "Suche",
            addBook: "Buch hinzufügen",
            remove: "Entfernen",
            update: "Aktualisieren",
            language: "Sprache",
            help: "Hilfe",
            terms: "Nutzungsbedingungen",
            privacy: "Datenschutzrichtlinie",
        },
        it: {
            welcome: "Benvenuto nel nostro sito!",
            logout: "Disconnettersi",
            login: "Accedi",
            signup: "Iscriviti",
            home: "Home",
            about: "Chi siamo",
            contact: "Contatto",
            books: "Libri",
            cart: "Carrello",
            profile: "Profilo",
            settings: "Impostazioni",
            search: "Cerca",
            addBook: "Aggiungi libro",
            remove: "Rimuovi",
            update: "Aggiorna",
            language: "Lingua",
            help: "Aiuto",
            terms: "Termini di servizio",
            privacy: "Informativa sulla privacy",
        },
        pt: {
            welcome: "Bem-vindo ao nosso site!",
            logout: "Sair",
            login: "Entrar",
            signup: "Inscrever-se",
            home: "Início",
            about: "Sobre nós",
            contact: "Contato",
            books: "Livros",
            cart: "Carrinho",
            profile: "Perfil",
            settings: "Configurações",
            search: "Pesquisar",
            addBook: "Adicionar livro",
            remove: "Remover",
            update: "Atualizar",
            language: "Idioma",
            help: "Ajuda",
            terms: "Termos de serviço",
            privacy: "Política de privacidade",
        },
        zh: {
            welcome: "欢迎来到我们的网站！",
            logout: "登出",
            login: "登录",
            signup: "注册",
            home: "首页",
            about: "关于我们",
            contact: "联系我们",
            books: "书籍",
            cart: "购物车",
            profile: "个人资料",
            settings: "设置",
            search: "搜索",
            addBook: "添加书籍",
            remove: "移除",
            update: "更新",
            language: "语言",
            help: "帮助",
            terms: "服务条款",
            privacy: "隐私政策",
        },
        ar: {
            welcome: "مرحبًا بك في موقعنا!",
            logout: "تسجيل الخروج",
            login: "تسجيل الدخول",
            signup: "إنشاء حساب",
            home: "الرئيسية",
            about: "معلومات عنا",
            contact: "اتصل بنا",
            books: "الكتب",
            cart: "عربة التسوق",
            profile: "الملف الشخصي",
            settings: "الإعدادات",
            search: "بحث",
            addBook: "إضافة كتاب",
            remove: "إزالة",
            update: "تحديث",
            language: "اللغة",
            help: "مساعدة",
            terms: "شروط الخدمة",
            privacy: "سياسة الخصوصية",
        },
        ru: {
            welcome: "Добро пожаловать на наш сайт!",
            logout: "Выйти",
            login: "Войти",
            signup: "Зарегистрироваться",
            home: "Главная",
            about: "О нас",
            contact: "Контакты",
            books: "Книги",
            cart: "Корзина",
            profile: "Профиль",
            settings: "Настройки",
            search: "Поиск",
            addBook: "Добавить книгу",
            remove: "Удалить",
            update: "Обновить",
            language: "Язык",
            help: "Помощь",
            terms: "Условия обслуживания",
            privacy: "Политика конфиденциальности",
        },
        ja: {
            welcome: "私たちのサイトへようこそ！",
            logout: "ログアウト",
            login: "ログイン",
            signup: "サインアップ",
            home: "ホーム",
            about: "私たちについて",
            contact: "お問い合わせ",
            books: "本",
            cart: "カート",
            profile: "プロフィール",
            settings: "設定",
            search: "検索",
            addBook: "本を追加",
            remove: "削除",
            update: "更新",
            language: "言語",
            help: "ヘルプ",
            terms: "利用規約",
            privacy: "プライバシーポリシー",
        },
        ko: {
            welcome: "우리 사이트에 오신 것을 환영합니다!",
            logout: "로그아웃",
            login: "로그인",
            signup: "회원가입",
            home: "홈",
            about: "회사 소개",
            contact: "문의하기",
            books: "도서",
            cart: "장바구니",
            profile: "프로필",
            settings: "설정",
            search: "검색",
            addBook: "도서 추가",
            remove: "제거",
            update: "업데이트",
            language: "언어",
            help: "도움말",
            terms: "서비스 약관",
            privacy: "개인정보 처리방침",
        },
    };

          
    return (
        <div style={{ maxWidth: 400, margin: "0 auto", padding: 24, border: "1px solid #eee", borderRadius: 8, background: "#fafafa" }}>
            <h1 style={{ textAlign: "center", fontSize: "24px", marginBottom: 24 }}>{Translate[Language].welcome}</h1>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                <button style={{ padding: "8px 0", fontWeight: "bold" }}>{Translate[Language].home}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].about}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].contact}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].books}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].cart}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].profile}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].settings}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].search}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].addBook}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].remove}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].update}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].language}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].help}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].terms}</button>
                <button style={{ padding: "8px 0" }}>{Translate[Language].privacy}</button>
                <button style={{ padding: "8px 0", background: "#1976d2", color: "#fff", border: "none", borderRadius: 4 }}>{Translate[Language].login}</button>
                <button style={{ padding: "8px 0", background: "#388e3c", color: "#fff", border: "none", borderRadius: 4 }}>{Translate[Language].signup}</button>
                <button style={{ padding: "8px 0", background: "#d32f2f", color: "#fff", border: "none", borderRadius: 4 }}>{Translate[Language].logout}</button>
            </div>
            <div style={{
                display:"flex",
                justifyContent:"center",
                alignItems:"center",
                padding:"10px"
            }}>
            <label style={{color: "black"}} htmlFor="Theme">{theme}</label>
            <input type="checkbox" 
             checked ={theme =="dark"}
             onChange={toggleTheme}
            />
            </div>
        </div>
    )
}
export default Wellcome;
